age 			= input("[+] Enter your age		    :  ")
date 			= input("[+] Enter the day you born 	    :  ")
education 		= input("[+] Enter your education 	    :  ")
certificate 	        = input("[+] Enter your certificate 	    :  ")
certificate1	        = input("[+] Enter your another certificate  :  ")

print("\n")
print("တကယ္အတည္တြဲခ်င္ပါတယ္ .. အသက္က "+age+" ႏွစ္ပါ "+date+" born ပါ"+" (ဓမၼ-ေသာက-အင္း၀-ရာဇာ)မလြတ္မွာစုိးလုိ႔ထည့္ေပးထားပါတယ္")
print("\n")
print("ပညာေရးလဲမဆုိးပါဘူး .. "+education+" တက္ေနပါတယ္"+certificate+" သင္တန္းလဲျပီးပါျပီ "+certificate1+" လဲတက္ေနပါတယ္")
print("\n")
print("ရုပ္ရည္လဲမဆိုးပါဘူးေနာ္ .. ပိုက္ဆံလဲအသင့္အတင့္ရွိပါတယ္ .. reply လဲျမန္ပါတယ္ .. seen လဲျမန္ပါတယ္ .. အိမ္မွဴကိစၥလဲႏိုင္ပါတယ္ .. မင္းမ်က္ႏွာကမၻာထင္ျပီးခ်စ္မဲ့သူမိ်ဳးပါ")
print("\n")
print("ro လဲ ro တတ္ပါတယ္ .. surprise ေတြလဲမၾကာမၾကာလုပ္ေပးတတ္ပါတယ္ .. LDRS ဆုိရင္လဲသစၥာရွိေပးႏိုင္ပါတယ္ .. Anniversary 2 years ျပည့္ရင္ အိမ္နဲ့ပါအသိေပးပါမယ္")
print("\n")
print("အတည္ေပါက္ေစ်းဗန္းပါ")
print("\n")
